version: 0.2

phases:
  install:    
    on-failure: ABORT | CONTINUE
    runtime-versions:
      java: openjdk11      
    commands:
      - echo install     
  pre_build:    
    on-failure: ABORT | CONTINUE
    commands:
      - echo pre_build          
  build:    
    on-failure: ABORT | CONTINUE
    commands:
      - mvn package
      - echo build    
  post_build:    
    on-failure: ABORT | CONTINUE
    commands:
      - echo post_build
      
artifacts:
  files:
    - target/spring-boot-todo-rest-api-h2-aws-codepipeline-0.0.1-SNAPSHOT.jar 